const $=id=>document.getElementById(id);const samples=[['キオクシア投資再分析','investment_analysis',{ticker:'285A.T',company_name:'キオクシアホールディングス'}],['企業戦略分析','company_analysis',{company_name:'Honda'}],['福利厚生4.0','hr_strategy_review',{project:'福利厚生4.0'}],['採用戦略レビュー','hr_strategy_review',{project:'採用戦略'}],['新規事業アイデア','idea_generation',{theme:'AI Company'}],['学習教材生成','learning_material',{topic:'経営戦略'}]];let agents={agents:[]},workflows={workflows:[]};
async function loadData(){try{agents=await fetch('data/agents.json').then(r=>r.json());workflows=await fetch('data/workflows.json').then(r=>r.json())}catch(e){console.warn(e)}renderWorkflows();renderAgents();renderSamples();makeTask()}
function renderWorkflows(){const sel=$('taskWorkflow');sel.innerHTML=workflows.workflows.map(w=>`<option value="${esc(w.id)}">${esc(w.name||w.id)}</option>`).join('');sel.onchange=()=>{renderWorkflow();makeTask()};renderWorkflow()}
function renderAgents(){$('agentList').innerHTML=(agents.agents||[]).map(a=>`<div class="agent-card"><b>${esc(a.display_name)}</b><p>${esc(a.role)}</p><small>v${esc(a.version)} / ${esc(a.enabled)} / ${esc(a.executor)} / ${esc(a.provider)} / ${esc(a.model)}</small><p>${(a.tags||[]).map(esc).join(' ')}</p></div>`).join('')}
function renderWorkflow(){const wf=(workflows.workflows||[]).find(w=>w.id===$('taskWorkflow').value)||workflows.workflows[0];$('workflowViewer').innerHTML=wf?wf.steps.map(s=>`<div class="step-card"><b>${esc(s.id)}</b> → ${esc(s.agent)}<br><small>depends_on: ${(s.depends_on||[]).join(', ')||'none'} / output: ${esc(s.output_key||s.id)} / group: ${esc(s.concurrency_group||'')}</small></div>`).join(''):'workflow data not loaded'}
function renderSamples(){const box=$('samples');box.innerHTML=samples.map((s,i)=>`<button data-i="${i}">${s[0]}</button>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{const s=samples[b.dataset.i];$('taskWorkflow').value=s[1];$('taskTarget').value=JSON.stringify(s[2]);$('taskRequest').value=s[0]+'をHOS AI Companyで実行してください。';renderWorkflow();makeTask()})}
function renderModeNotice(){const v=$('taskMode').value;const n=$('geminiFreeNotice');if(!n)return;if(v==='gemini'){n.innerHTML='Gemini無料枠: 最大Agent数 5 / 推定Call数 5。無料枠の上限に達する可能性があります。APIキー(GEMINI_API_KEY)が必要です。個人情報・機密情報を入力しないでください。無料枠は保証されません。';}else{n.textContent='';}}
function makeTask(){renderModeNotice();let target;try{target=JSON.parse($('taskTarget').value)}catch{target={name:$('taskTarget').value}}const task={task_id:'HOS-'+new Date().toISOString().replace(/[-:.TZ]/g,'').slice(0,14),workflow:$('taskWorkflow').value||'investment_analysis',request:$('taskRequest').value,target,project:$('taskProject').value,priority:$('taskPriority').value,due_date:$('taskDue').value||null,execution_mode:$('taskMode').value,executor:$('taskMode').value==='gemini'?'gemini':($('taskMode').value==='openai'?'openai':($('taskMode').value==='mock'?'mock':'json')),required_outputs:$('taskOutputs').value.split(',').map(x=>x.trim()).filter(Boolean),constraints:$('taskConstraints').value.split('\n').map(x=>x.trim()).filter(Boolean),approval_gate:$('taskApproval').checked};$('taskPreview').textContent=JSON.stringify(task,null,2);return task}
function download(){const blob=new Blob([$('taskPreview').textContent],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='hos-ai-company-task.json';a.click();URL.revokeObjectURL(a.href)}
function renderRun(){let d;try{d=JSON.parse($('runJson').value)}catch(e){$('runView').innerHTML='<p class="notice">JSON parse error: '+esc(e.message)+'</p>';return}$('runView').innerHTML=`<div class="run-card"><h3>${esc(d.run_id||d.task_id||'JSON')}</h3><p>Status: ${esc(d.status||'n/a')}</p><pre class="json-preview">${esc(JSON.stringify(d,null,2))}</pre></div>`}
function esc(x){return String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.addEventListener('input',e=>{if(e.target.closest('#taskRequest,#taskProject,#taskTarget,#taskPriority,#taskDue,#taskMode,#taskOutputs,#taskConstraints,#taskApproval'))makeTask()});$('makeTask').onclick=makeTask;$('copyTask').onclick=()=>navigator.clipboard?.writeText($('taskPreview').textContent);$('downloadTask').onclick=download;$('saveTask').onclick=()=>localStorage.setItem('hos.aiCompany.lastTask',$('taskPreview').textContent);$('renderRun').onclick=renderRun;$('runFile').onchange=e=>{const f=e.target.files[0];if(f){f.text().then(t=>{$('runJson').value=t;renderRun()})}};loadData();
if(typeof module!=='undefined')module.exports={makeTask:()=>({}),esc};
