const DIVIDEND_STORAGE_KEY="hosDividendEmpireState";
const SORT_LABELS={marketValue:"評価額",annualDividend:"年間配当",dividendYield:"配当利回り",totalYield:"優待込み利回り",unrealizedGain:"含み損益"};
function yen(v){return new Intl.NumberFormat("ja-JP",{style:"currency",currency:"JPY",maximumFractionDigits:0}).format(Math.round(Number(v)||0))}
function num(v){return new Intl.NumberFormat("ja-JP",{maximumFractionDigits:1}).format(Number(v)||0)}
function pct(v){return `${num(v)}%`}
function clamp(v,min=0,max=100){return Math.max(min,Math.min(max,v))}
function readDividendState(){try{return JSON.parse(localStorage.getItem(DIVIDEND_STORAGE_KEY))||null}catch{return null}}
function cloneDefaults(){return{settings:structuredClone(DIVIDEND_EMPIRE_DEFAULT_SETTINGS),holdings:structuredClone(DIVIDEND_EMPIRE_DEFAULT_HOLDINGS),sortKey:"marketValue",sortDir:"desc"}}
function getState(){return readDividendState()||cloneDefaults()}
function saveState(state){localStorage.setItem(DIVIDEND_STORAGE_KEY,JSON.stringify(state))}
function holdingMetrics(h){const marketValue=h.shares*h.currentPrice;const principal=h.shares*h.acquisitionPrice;const annualDividend=h.shares*h.annualDividendPerShare;const annualBenefit=h.benefitFaceValue*h.benefitUsageRate;return{...h,marketValue,principal,unrealizedGain:marketValue-principal,annualDividend,annualBenefit,dividendYield:marketValue?annualDividend/marketValue*100:0,totalYield:marketValue?(annualDividend+annualBenefit)/marketValue*100:0}}
function totals(state){const rows=state.holdings.map(holdingMetrics);const holdingAssets=rows.reduce((s,r)=>s+r.marketValue,0);const totalAssets=Number(state.settings.totalAssets)||holdingAssets;const principal=Number(state.settings.investedPrincipal)||rows.reduce((s,r)=>s+r.principal,0);const annualDividend=rows.reduce((s,r)=>s+r.annualDividend,0);const annualBenefit=rows.reduce((s,r)=>s+r.annualBenefit,0);return{rows,totalAssets,principal,unrealizedGain:totalAssets-principal,annualDividend,annualBenefit,annualReturn:annualDividend+annualBenefit,dividendYield:totalAssets?annualDividend/totalAssets*100:0,totalYield:totalAssets?(annualDividend+annualBenefit)/totalAssets*100:0,targetProgress:totalAssets/state.settings.targetAssetAt60*100,freedom:state.settings.annualLivingCost?(annualDividend+annualBenefit)/state.settings.annualLivingCost*100:0}}
function inputAttrs(path,value,step=1){return`data-path="${path}" type="number" step="${step}" value="${value}"`}
function renderDividendEmpire(){const root=document.getElementById("dividendApp");if(!root)return;const state=getState();const t=totals(state);const sorted=[...t.rows].sort((a,b)=>((b[state.sortKey]||0)-(a[state.sortKey]||0))*(state.sortDir==="desc"?1:-1));
root.innerHTML=`<section class="dividend-hero"><p class="eyebrow gold">Dividend Empire</p><h2>ひろちゃん配当帝国</h2><p>60歳で「好きだから働く」を実現する資産運用OS</p><div class="sample-note">このページはローカルのサンプルデータと入力値で動く初期版です。株価・配当・優待は実データではありません。</div><div class="dividend-actions"><button id="saveDividendState">入力内容を保存</button><button class="copy" id="resetDividendState">サンプルデータに戻す</button></div></section>
<section class="dividend-panel"><h2>主要指標</h2><div class="metric-grid">${metric("金融資産総額",yen(t.totalAssets),"settings.totalAssets",state.settings.totalAssets)}${metric("投資元本",yen(t.principal),"settings.investedPrincipal",state.settings.investedPrincipal)}${metric("含み損益",yen(t.unrealizedGain),null,null,t.unrealizedGain>=0)}${metric("年間予想配当",yen(t.annualDividend))}${metric("年間優待価値",yen(t.annualBenefit))}${metric("年間総還元額",yen(t.annualReturn))}${metric("配当利回り",pct(t.dividendYield))}${metric("優待込み総合利回り",pct(t.totalYield))}${metric("2億円目標進捗",pct(t.targetProgress))}</div></section>
<section class="dividend-panel freedom"><h2>人生自由度メーター</h2><div class="freedom-grid"><div><label>年間生活費<input ${inputAttrs("settings.annualLivingCost",state.settings.annualLivingCost)}></label><p>年間予想配当 <b>${yen(t.annualDividend)}</b> / 年間優待価値 <b>${yen(t.annualBenefit)}</b></p><strong>${pct(t.freedom)}</strong><div class="progress"><span style="width:${clamp(t.freedom)}%"></span></div><p class="freedom-message">${t.freedom>=100?"生活費を資産収入でカバーできています":`あと年間${yen(state.settings.annualLivingCost-t.annualReturn)}で生活費を資産収入だけでカバーできます`}</p></div></div></section>
<section class="dividend-panel"><h2>保有銘柄一覧</h2><div class="sortbar"><label>並べ替え<select id="sortKey">${Object.entries(SORT_LABELS).map(([k,l])=>`<option value="${k}" ${state.sortKey===k?"selected":""}>${l}</option>`).join("")}</select></label><button id="sortDir" class="copy">${state.sortDir==="desc"?"降順":"昇順"}</button></div><div class="table-wrap"><table class="holdings-table"><thead><tr>${["銘柄コード","銘柄名","セクター","保有株数","取得単価","現在株価","評価額","含み損益","年間配当","優待額面","想定利用率","年間優待価値","配当利回り","優待込み利回り","保有目的","ステータス"].map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${sorted.map(r=>row(r,state.holdings.findIndex(h=>h.code===r.code))).join("")}</tbody></table></div></section>
<section class="dividend-columns"><div class="dividend-panel"><h2>セクター構成</h2>${barList(group(t.rows,"sector","marketValue"),t.rows.reduce((s,r)=>s+r.marketValue,0),true)}</div><div class="dividend-panel"><h2>年間配当・優待構成</h2><div class="stack-list">${t.rows.map(r=>stackRow(r)).join("")}</div></div></section>
<section class="dividend-columns"><div class="dividend-panel"><h2>目標進捗</h2>${state.settings.milestones.map(m=>progressLine(`${m.age}歳：${yen(m.amount)}`,t.totalAssets/m.amount*100)).join("")}</div><div class="dividend-panel"><h2>配当で買えるもの</h2>${lifestyle(state.settings.dividendLifestyleGoals,t.annualDividend)}</div></section>
<section class="dividend-panel"><h2>優待価値の考え方</h2><p>優待価値は額面ではなく、本人が実際に使うと見込まれる金額で管理します。例：額面10,000円の優待でも半分しか使わない場合は、想定利用率50%として年間優待価値5,000円で登録します。</p></section>
<section class="dividend-note">本画面は資産管理と長期計画のための参考情報です。表示される株価、配当、優待価値は入力値またはサンプルデータに基づきます。投資判断は最新の企業情報と市場情報を確認して行ってください。</section>`;bindDividend(root,state)}
function metric(label,value,path,raw,positive){return`<article class="empire-metric ${positive===false?'negative':''}"><span>${label}</span><strong>${value}</strong>${path?`<input ${inputAttrs(path,raw)} aria-label="${label}">`:""}</article>`}
function row(r,i){return`<tr><td>${r.code}</td><td>${r.name}</td><td>${r.sector}</td><td><input ${inputAttrs(`holdings.${i}.shares`,r.shares)}></td><td><input ${inputAttrs(`holdings.${i}.acquisitionPrice`,r.acquisitionPrice)}></td><td><input ${inputAttrs(`holdings.${i}.currentPrice`,r.currentPrice)}></td><td>${yen(r.marketValue)}</td><td class="${r.unrealizedGain<0?'negative':'positive'}">${yen(r.unrealizedGain)}</td><td>${yen(r.annualDividend)}</td><td><input ${inputAttrs(`holdings.${i}.benefitFaceValue`,r.benefitFaceValue)}></td><td><input ${inputAttrs(`holdings.${i}.benefitUsageRate`,r.benefitUsageRate,0.01)}></td><td>${yen(r.annualBenefit)}</td><td>${pct(r.dividendYield)}</td><td>${pct(r.totalYield)}</td><td>${r.purpose}</td><td>${r.status}</td></tr>`}
function group(rows,key,val){return Object.values(rows.reduce((a,r)=>{a[r[key]]??={label:r[key],value:0};a[r[key]].value+=r[val];return a},{})).sort((a,b)=>b.value-a.value)}
function barList(items,total,showYen){return`<div class="bar-list">${items.map(i=>progressLine(`${i.label} ${showYen?yen(i.value):''}`,total?i.value/total*100:0)).join("")}</div>`}
function progressLine(label,p){return`<div class="progress-line"><div><b>${label}</b><span>${pct(p)}</span></div><div class="progress"><span style="width:${clamp(p)}%"></span></div></div>`}
function stackRow(r){const total=r.annualDividend+r.annualBenefit;return`<div class="stack-row"><div><b>${r.name}</b><span>配当 ${yen(r.annualDividend)} / 優待 ${yen(r.annualBenefit)}</span></div><div class="stack"><span class="div" style="width:${total?r.annualDividend/total*100:0}%"></span><span class="ben" style="width:${total?r.annualBenefit/total*100:0}%"></span></div></div>`}
function lifestyle(goals,annualDividend){const achieved=goals.filter(g=>annualDividend>=g.amount);const next=goals.find(g=>annualDividend<g.amount);return`<h3>達成済み</h3><ul>${(achieved.length?achieved:[{amount:0,label:"まだ最初の目標に向けて育成中"}]).map(g=>`<li>${yen(g.amount)}：${g.label}</li>`).join("")}</ul><h3>次の目標</h3><p>${next?`${yen(next.amount)}：${next.label}（あと${yen(next.amount-annualDividend)}）`:"すべての配当ライフ目標を達成しています。"}</p>`}
function setPath(obj,path,value){const parts=path.split('.');let cur=obj;for(let i=0;i<parts.length-1;i++)cur=cur[parts[i]];cur[parts.at(-1)]=Number(value)}
function bindDividend(root,state){root.querySelectorAll("input[data-path]").forEach(input=>input.addEventListener("change",e=>{setPath(state,e.target.dataset.path,e.target.value);saveState(state);renderDividendEmpire()}));root.querySelector("#sortKey").onchange=e=>{state.sortKey=e.target.value;saveState(state);renderDividendEmpire()};root.querySelector("#sortDir").onclick=()=>{state.sortDir=state.sortDir==="desc"?"asc":"desc";saveState(state);renderDividendEmpire()};root.querySelector("#saveDividendState").onclick=()=>{saveState(state);showToast("Dividend Empireの入力内容を保存しました")};root.querySelector("#resetDividendState").onclick=()=>{localStorage.removeItem(DIVIDEND_STORAGE_KEY);renderDividendEmpire();showToast("サンプルデータに戻しました")}}
document.addEventListener("DOMContentLoaded",renderDividendEmpire);
