watchlist:
  - code: "5713"
    name: "住友金属鉱山"
    volatility: "high"
  - code: "5711"
    name: "三菱マテリアル"
    volatility: "medium"
  - code: "2768"
    name: "双日"
    volatility: "medium"
  - code: "7456"
    name: "松田産業"
    volatility: "medium"
  - code: "4063"
    name: "信越化学工業"
    volatility: "large"
  - code: "6981"
    name: "村田製作所"
    volatility: "large"
  - code: "8001"
    name: "伊藤忠商事"
    volatility: "large"
  - code: "8002"
    name: "丸紅"
    volatility: "large"
  - code: "7832"
    name: "バンダイナムコHD"
    volatility: "medium"
  - code: "9697"
    name: "カプコン"
    volatility: "medium"
  - code: "9684"
    name: "スクウェア・エニックスHD"
    volatility: "medium"
  - code: "5698"
    name: "エンビプロHD"
    volatility: "high"
